### PR TITLE
Fixes to simulation staging mechanism

### PR DESCRIPTION
**Pull request by Gerry1135**
This is my current, work-in-progress branch for fixes to the simulation staging.  I'll let you know once I think it is ready for merging...

### CODE REVIEW

**Comment by Gerry1135** [comment]
Looks to be working ok but I'm going to do a dev release to get it a bit more of a test.
I'm also still working on a change to fix the issues when the root part gets decoupled.

**Comment by Gerry1135** [comment]
The changes to fix the root decoupling are proving very awkward.  I'm almost at the point where I'm going to give up on a "quick fix" solution and do it "properly" instead because the quick fixes 

This will involve implementing a new VesselSim object which will allow the ActivateStage function to create a new VesselSim for each subtree of the vessel that gets decoupled, discard any that are pointless (e.g. have no engines and/or fuel left), and then continue simulating the remaining Vessels.  This will involve another considerable change to how the simulation works (it will need to keep a and how it represents the output data, e.g. after activating a decoupler it is quite possible that both the sub-vessels are still viable craft with multiple stages.

I'll let you know later if I'm giving up on the quick fix as, if I do then it is probably worth merging this as it is.

**Comment by CYBUTEK** [comment]
The VesselSim object route seems to be the next logical step for the simulation code to progress.  The only problem with this is that it has the possibility of causing confusion where the player doesn't have a very good understanding of how staging works.  Or plans to manage fuel flow manually mid-flight.  Replacing one problem of the player not having deltaV stats, to complaining about the deltaV being wrong.  But these are issues which will have to be solved through UI design and other factors that will become apparent as development progresses.

**Comment by Gerry1135** [comment]
Sorry for the delay, got a bit tied up yesterday.  I am giving up on the quick fix for the root decoupling issues so this can be merged now.

**Comment by Gerry1135** [comment]
I created a pull request on v1 with the relevant changes (just Simulation.cs) but, for some reason, git decided to change the line endings on most of the files.  I then noticed that v1 doesn't actually display the "active" stage during flight (when the active engines are different to what they should be for the current stage) so I couldn't fully test the changes.  Then, after making another change, my local v1 repo got badly confused and wouldn't let me discard the changes on one of the files.

**Comment by Gerry1135** [comment]
That last commit fixes the bug reported in:
http://forum.kerbalspaceprogram.com/threads/18230-0-24-2-Kerbal-Engineer-Redux-v0-6-2-9-and-v1-0-3?p=1347135&viewfull=1#post1347135

**Comment by CYBUTEK** [comment]
I want to bring out what may be the final update to 0.6 unless some big bugs crop up.  Is this pull ready to be merged?

**Comment by Gerry1135** [comment]
Yes, sure.  I've started the VesselSim stuff on the 1.0 codebase though it will probably take me a while as I'm currently in a rather busy RL phase...

**Pull request merged**
